#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteCamposDealer.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TesteCamposDealer")]
	public partial class DBTesteCamposDealerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    partial void InsertVenda(Venda instance);
    partial void UpdateVenda(Venda instance);
    partial void DeleteVenda(Venda instance);
    partial void InsertHistorico_Produto(Historico_Produto instance);
    partial void UpdateHistorico_Produto(Historico_Produto instance);
    partial void DeleteHistorico_Produto(Historico_Produto instance);
    #endregion
		
		public DBTesteCamposDealerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TesteCamposDealerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBTesteCamposDealerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTesteCamposDealerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTesteCamposDealerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTesteCamposDealerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produto
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<Venda> Venda
		{
			get
			{
				return this.GetTable<Venda>();
			}
		}
		
		public System.Data.Linq.Table<Historico_Produto> Historico_Produto
		{
			get
			{
				return this.GetTable<Historico_Produto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCliente;
		
		private string _nomeCliente;
		
		private string _endereco;
		
		private System.DateTime _dthRegistro;
		
		private EntitySet<Venda> _Venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OnnomeClienteChanging(string value);
    partial void OnnomeClienteChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OndthRegistroChanging(System.DateTime value);
    partial void OndthRegistroChanged();
    #endregion
		
		public Cliente()
		{
			this._Venda = new EntitySet<Venda>(new Action<Venda>(this.attach_Venda), new Action<Venda>(this.detach_Venda));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeCliente", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string nomeCliente
		{
			get
			{
				return this._nomeCliente;
			}
			set
			{
				if ((this._nomeCliente != value))
				{
					this.OnnomeClienteChanging(value);
					this.SendPropertyChanging();
					this._nomeCliente = value;
					this.SendPropertyChanged("nomeCliente");
					this.OnnomeClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dthRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime dthRegistro
		{
			get
			{
				return this._dthRegistro;
			}
			set
			{
				if ((this._dthRegistro != value))
				{
					this.OndthRegistroChanging(value);
					this.SendPropertyChanging();
					this._dthRegistro = value;
					this.SendPropertyChanged("dthRegistro");
					this.OndthRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Venda", Storage="_Venda", ThisKey="idCliente", OtherKey="idCliente")]
		internal EntitySet<Venda> Venda
		{
			get
			{
				return this._Venda;
			}
			set
			{
				this._Venda.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produto")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProduto;
		
		private string _dscProduto;
		
		private double _vlrProduto;
		
		private EntitySet<Venda> _Venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProdutoChanging(int value);
    partial void OnidProdutoChanged();
    partial void OndscProdutoChanging(string value);
    partial void OndscProdutoChanged();
    partial void OnvlrProdutoChanging(double value);
    partial void OnvlrProdutoChanged();
    #endregion
		
		public Produto()
		{
			this._Venda = new EntitySet<Venda>(new Action<Venda>(this.attach_Venda), new Action<Venda>(this.detach_Venda));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idProduto
		{
			get
			{
				return this._idProduto;
			}
			set
			{
				if ((this._idProduto != value))
				{
					this.OnidProdutoChanging(value);
					this.SendPropertyChanging();
					this._idProduto = value;
					this.SendPropertyChanged("idProduto");
					this.OnidProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dscProduto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string dscProduto
		{
			get
			{
				return this._dscProduto;
			}
			set
			{
				if ((this._dscProduto != value))
				{
					this.OndscProdutoChanging(value);
					this.SendPropertyChanging();
					this._dscProduto = value;
					this.SendPropertyChanged("dscProduto");
					this.OndscProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrProduto")]
		public double vlrProduto
		{
			get
			{
				return this._vlrProduto;
			}
			set
			{
				if ((this._vlrProduto != value))
				{
					this.OnvlrProdutoChanging(value);
					this.SendPropertyChanging();
					this._vlrProduto = value;
					this.SendPropertyChanged("vlrProduto");
					this.OnvlrProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Venda", Storage="_Venda", ThisKey="idProduto", OtherKey="idProduto")]
		internal EntitySet<Venda> Venda
		{
			get
			{
				return this._Venda;
			}
			set
			{
				this._Venda.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_Venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venda")]
	public partial class Venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idVenda;
		
		private int _idCliente;
		
		private int _idProduto;
		
		private System.DateTime _dthRegistro;
		
		private double _vlrTotal;
		
		private int _qtdeProduto;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidVendaChanging(int value);
    partial void OnidVendaChanged();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OnidProdutoChanging(int value);
    partial void OnidProdutoChanged();
    partial void OndthRegistroChanging(System.DateTime value);
    partial void OndthRegistroChanged();
    partial void OnvlrTotalChanging(double value);
    partial void OnvlrTotalChanged();
    partial void OnqtdeProdutoChanging(int value);
    partial void OnqtdeProdutoChanged();
    #endregion
		
		public Venda()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Produto = default(EntityRef<Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVenda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idVenda
		{
			get
			{
				return this._idVenda;
			}
			set
			{
				if ((this._idVenda != value))
				{
					this.OnidVendaChanging(value);
					this.SendPropertyChanging();
					this._idVenda = value;
					this.SendPropertyChanged("idVenda");
					this.OnidVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduto", DbType="Int NOT NULL")]
		public int idProduto
		{
			get
			{
				return this._idProduto;
			}
			set
			{
				if ((this._idProduto != value))
				{
					if (this._Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProdutoChanging(value);
					this.SendPropertyChanging();
					this._idProduto = value;
					this.SendPropertyChanged("idProduto");
					this.OnidProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dthRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime dthRegistro
		{
			get
			{
				return this._dthRegistro;
			}
			set
			{
				if ((this._dthRegistro != value))
				{
					this.OndthRegistroChanging(value);
					this.SendPropertyChanging();
					this._dthRegistro = value;
					this.SendPropertyChanged("dthRegistro");
					this.OndthRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrTotal")]
		public double vlrTotal
		{
			get
			{
				return this._vlrTotal;
			}
			set
			{
				if ((this._vlrTotal != value))
				{
					this.OnvlrTotalChanging(value);
					this.SendPropertyChanging();
					this._vlrTotal = value;
					this.SendPropertyChanged("vlrTotal");
					this.OnvlrTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtdeProduto")]
		public int qtdeProduto
		{
			get
			{
				return this._qtdeProduto;
			}
			set
			{
				if ((this._qtdeProduto != value))
				{
					this.OnqtdeProdutoChanging(value);
					this.SendPropertyChanging();
					this._qtdeProduto = value;
					this.SendPropertyChanged("qtdeProduto");
					this.OnqtdeProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Venda", Storage="_Cliente", ThisKey="idCliente", OtherKey="idCliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Venda.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Venda.Add(this);
						this._idCliente = value.idCliente;
					}
					else
					{
						this._idCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Venda", Storage="_Produto", ThisKey="idProduto", OtherKey="idProduto", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.Venda.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.Venda.Add(this);
						this._idProduto = value.idProduto;
					}
					else
					{
						this._idProduto = default(int);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Historico_Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idHistorico;
		
		private int _idProduto;
		
		private string _dscProduto;
		
		private double _vlrProduto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidHistoricoChanging(int value);
    partial void OnidHistoricoChanged();
    partial void OnidProdutoChanging(int value);
    partial void OnidProdutoChanged();
    partial void OndscProdutoChanging(string value);
    partial void OndscProdutoChanged();
    partial void OnvlrProdutoChanging(double value);
    partial void OnvlrProdutoChanged();
    #endregion
		
		public Historico_Produto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHistorico", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idHistorico
		{
			get
			{
				return this._idHistorico;
			}
			set
			{
				if ((this._idHistorico != value))
				{
					this.OnidHistoricoChanging(value);
					this.SendPropertyChanging();
					this._idHistorico = value;
					this.SendPropertyChanged("idHistorico");
					this.OnidHistoricoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduto")]
		public int idProduto
		{
			get
			{
				return this._idProduto;
			}
			set
			{
				if ((this._idProduto != value))
				{
					this.OnidProdutoChanging(value);
					this.SendPropertyChanging();
					this._idProduto = value;
					this.SendPropertyChanged("idProduto");
					this.OnidProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dscProduto", CanBeNull=false)]
		public string dscProduto
		{
			get
			{
				return this._dscProduto;
			}
			set
			{
				if ((this._dscProduto != value))
				{
					this.OndscProdutoChanging(value);
					this.SendPropertyChanging();
					this._dscProduto = value;
					this.SendPropertyChanged("dscProduto");
					this.OndscProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrProduto")]
		public double vlrProduto
		{
			get
			{
				return this._vlrProduto;
			}
			set
			{
				if ((this._vlrProduto != value))
				{
					this.OnvlrProdutoChanging(value);
					this.SendPropertyChanging();
					this._vlrProduto = value;
					this.SendPropertyChanged("vlrProduto");
					this.OnvlrProdutoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
